add re-encode support for 2PASS and 2PASS VBR improvement
AOMediaCodec/SVT-AV1 pull request #1576
Opened 2020-11-13 08:35 UTC by kelvinhu325

#define FEATURE_RE_ENCODE         1 // Add re-encode support
 #define FIX_VBR_LAST_GOP_BITS     1 // Fix 2nd pass last small group too big frame size error
 #define FIX_ONE_MIN_QP_ALLOWED    1 // Set default min_qp_allowed=1 for VBR good quality
 #define FIX_ALLOW_SB128_2PASS_VBR 1 // To allow SB128x128 for 2pass VBR
 #define FIX_2PASS_VBR_4L_SUPPORT  1 // Add 2pass VBR 4L support
 #define FIX_FIRST_PASS_GM         1 // Fix the GM setting for the first pass

 Co-authored-by: Jing B <jing.b.li@intel.com>
 Co-authored-by: Naghdinezhad, Amir <Amir.Naghdinezhad@intel.com>
 Co-authored-by: huijuan.zhou <huijuan.zhou@intel.com>

# Description

# Issue

# Author(s)

# Performance impact

- [ ] quality
- [ ] memory
- [ ] speed
- [ ] 8 bit
- [ ] 10 bit
- [ ] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [ ] N/A

# Merge method
- [ ] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

2020-11-18 00:59 UTC, anaghdin requested changes

2020-11-18 03:20 UTC, kelvinhu325 commented on Source/Lib/Encoder/Globals/EbEncHandle.c
> +#if FEATURE_RE_ENCODE
OK, will make sure recode-loop=0 only for 2pass VBR in somewhere else, here is only for default value setting, BTW, doe is still needed set the default recode-loop value to 2?

2020-11-19 00:41 UTC, anaghdin approved these changes

2020-11-20 02:49 UTC, merged

2020-11-20 19:55 UTC, paulsgh commented
Tested objective-1 fast, 8bit and 10bit.
Fixed QP is lossless, VBR is not.

| | Speed Deviation  | BD-Rate   Deviation | Memory Deviation
-- | -- | -- | --
M0 - 8bit - 2pass - VBR| -13.48% | -7.94% | 12.54%
M4 - 8bit - 2pass - VBR| -11.23% | -7.22% | 10.19%
M8 - 8bit - 2pass - VBR| -7.69% | -5.41% | 13.70%
M0 - 10bit - 2pass - VBR| -15.46% | -8.43% | 9.76%
M4 - 10bit - 2pass - VBR| -12.56% | -7.28% | 9.76%
M8 - 10bit - 2pass - VBR| -7.84% | -5.35% | 5.67%
M0 - 8bit - 2pass| 0.45% | 0.00% | 0.00%
M0 - 10bit - 2pass| 0.34% | 0.00% | 2.51%
M0 - 8bit - 1pass| 0.38% | 0.00% | 0.09%
M4 - 8bit - 1pass| 0.37% | 0.00% | 0.06%
M8 - 8bit - 1pass| 0.48% | 0.00% | 0.02%
M0 - 10bit - 1pass| 0.14% | 0.00% | 0.04%
M4 - 10bit - 1pass| -0.17% | 0.00% | 0.02%
M8 - 10bit - 1pass| 0.01% | 0.00% | 0.03%

2020-11-22 14:30 UTC, kelvinhu325 commented
> Tested objective-1 fast, 8bit and 10bit.
> Fixed QP is lossless, VBR is not.
> 
> Speed Deviation	BD-Rate Deviation	Memory Deviation
> M0 - 8bit - 2pass - VBR	-13.48%	-7.94%	12.54%
> M4 - 8bit - 2pass - VBR	-11.23%	-7.22%	10.19%
> M8 - 8bit - 2pass - VBR	-7.69%	-5.41%	13.70%
> M0 - 10bit - 2pass - VBR	-15.46%	-8.43%	9.76%
> M4 - 10bit - 2pass - VBR	-12.56%	-7.28%	9.76%
> M8 - 10bit - 2pass - VBR	-7.84%	-5.35%	5.67%
> M0 - 8bit - 2pass	0.45%	0.00%	0.00%
> M0 - 10bit - 2pass	0.34%	0.00%	2.51%
> M0 - 8bit - 1pass	0.38%	0.00%	0.09%
> M4 - 8bit - 1pass	0.37%	0.00%	0.06%
> M8 - 8bit - 1pass	0.48%	0.00%	0.02%
> M0 - 10bit - 1pass	0.14%	0.00%	0.04%
> M4 - 10bit - 1pass	-0.17%	0.00%	0.02%
> M8 - 10bit - 1pass	0.01%	0.00%	0.03%

Yes, my quick local validation shows the memory increasing is mainly caused by the allowing SB128x128 for 2pass VBR change( macro FIX_ALLOW_SB128_2PASS_VBR), but it really bring big gain, we may trade off quality and memory.